spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        url-pattern: /*
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 1qaz@WSX
      # aop-patterns: com.tankinfo.*
      filters: stat, wall
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 60000
      validation-query: select 1
      validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      keep-alive: true
      phy-max-use-count: 1000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true


